Move the enable/disable setting under Advanced > Features > Experimental
woocommerce/woocommerce-order-source-attribution pull request #56
Opened 2023-07-03 21:21 UTC by JPry

### Changes proposed in this Pull Request:

Closes # .

_Replace this with a good description of your changes & reasoning._

### Checks:

* [ ] Does your code follow the [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) coding standards?

### Screenshots:

### Detailed test instructions:

1. 
2. 
3. 

### Additional details:

### Changelog entry

>

2023-07-06 08:30 UTC, rawdreeg requested changes
I think we need to update the "Settings" plugin action link as well. It still points to the old settings page
![Screenshot 2023-07-06 at 10 29 56](https://github.com/woocommerce/woocommerce-order-source-attribution/assets/4209011/b6689826-5170-43a0-8e2c-dd6cdb13e974)

2023-07-06 20:09 UTC, JPry commented
Thanks @rawdreeg, good catch! I added 1e8aa0a to address your feedback.

2023-07-07 09:12 UTC, budzanowski commented
Great work with the code. I am approving. I have some concerns that I have  described in the 

https://woomultichannel.wordpress.com/2023/05/25/design-i1-5-order-attribution/#comment-708

2023-07-07 09:13 UTC, budzanowski approved these changes

2023-07-07 09:20 UTC, rawdreeg approved these changes
Looks good! Thanks @JPry !

2023-07-07 15:07 UTC, merged